### ISSUE TITLE
Unexpected type ZodEffects

### ISSUE THREAD

**Issue by binajmen** [kiliman/remix-params-helper#15]
I have this schema to test the content of a JSON value.

```ts
import { z } from "zod";

const schema = z.object({
  name: z.string().refine((val) => {
    const values = Object.values(JSON.parse(val));
    return (
      values.length > 0 &&
      values.some((v) => typeof v === "string" && v.length > 0)
    );
  }, "You must fill in at least one language")
});

// error
schema.parse({ name: '{""}' });
schema.parse({ name: '{"en":""}' });
schema.parse({ name: '{"en":"","fr":""}' });

// success
schema.parse({ name: '{"en":"Game"}' });
schema.parse({ name: '{"en":"Game","fr":""}' });
schema.parse({ name: '{"en":"Game","fr":"Jeu"}' });
```

The schema works, but `remix-params-helper` does not seem to like it..

```
Error: Unexpected type ZodEffects for key name
    at processDef (/Users/benjamin/Projects/horeka/node_modules/remix-params-helper/dist/cjs/helper.js:149:15)
    at parseParams (/Users/benjamin/Projects/horeka/node_modules/remix-params-helper/dist/cjs/helper.js:19:9)
    at getParamsInternal (/Users/benjamin/Projects/horeka/node_modules/remix-params-helper/dist/cjs/helper.js:50:9)
    at getParams (/Users/benjamin/Projects/horeka/node_modules/remix-params-helper/dist/cjs/helper.js:84:12)
    at action (/Users/benjamin/Projects/horeka/build/index.js:993:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callRouteAction (/Users/benjamin/Projects/horeka/node_modules/@remix-run/server-runtime/data.js:36:14)
    at async handleDataRequest (/Users/benjamin/Projects/horeka/node_modules/@remix-run/server-runtime/server.js:110:18)
    at async requestHandler (/Users/benjamin/Projects/horeka/node_modules/@remix-run/server-runtime/server.js:45:20)
    at async /Users/benjamin/Projects/horeka/node_modules/@remix-run/express/server.js:45:22
```

**Comment by kiliman** [comment]
Thanks. The helper walks the schema to coerce your input into the schema. Apparently it's not handling the `refine()` function. 

Thanks for the repro. I'll get this fixed.

**Comment by binajmen** [comment]
Sir, you are awesome! 🚀
